apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aagakscluster-1aae"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aagakscluster-1aae"
  template:
    metadata:
      labels:
        app: "aagakscluster-1aae"
    spec:
      containers:
        - name: "aagakscluster-1aae"
          image: "aagaksreg.azurecr.io/aagakscluster"
          ports:
          - containerPort: 80