apiVersion: v1
kind: Service
metadata:
    name: "aagakscluster-1aae"
    labels:
        app: "aagakscluster-1aae"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aagakscluster-1aae"